AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  GetIntradayPricesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      CodeUri: s3://aws-staging-bucket/d8fea14d9321f7ce85eb0ee0fd6a6c09
      Runtime: nodejs10.x
      MemorySize: 256
      Timeout: 120
      Policies:
      - AWSLambdaExecute
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - secretsmanager:GetSecretValue
          - cognito-idp:AdminInitiateAuth
          Resource: '*'
      Events:
        ScheduledExec:
          Type: Schedule
          Properties:
            Schedule: rate(30 minutes)
            Name: GetIntradayPricesSchedule
            Enabled: true
